/** Central UI labels for the analysis module (محور → تصویب → ارجاع → تحلیل). */

export const ANALYSIS_TERMS = {
  axis: "محور",
  axisDescription: "شرح محور",
  axisRequired: "محور الزامی است",
  axisMaxLength: (max) => `محور حداکثر ${max} کاراکتر باشد`,
  descriptionRequired: "شرح محور الزامی است",
  descriptionMaxLength: (max) => `شرح محور حداکثر ${max} کاراکتر باشد`,
  suggestedDeadline: "مهلت پیشنهادی",
  suggestedDeadlineHint: "اختیاری — از تقویم شمسی انتخاب کنید؛ فقط امروز یا روزهای بعد مجاز است",
  suggestedDeadlineInvalid: "مهلت پیشنهادی نامعتبر است. لطفاً تاریخ را فقط از تقویم انتخاب کنید (نوشتن دستی ممکن است خطا بدهد).",
  suggestedDeadlinePast: "مهلت پیشنهادی نمی‌تواند قبل از امروز باشد.",
  missionDeadline: "مهلت مأموریت",
  ratified: "تصویب شده",
  ratify: "تصویب",
  ratifyDecision: "تصمیم تصویب",
  ratifyPageTitle: "تصویب محور",
  ratifyHelpTitle: "راهنمای تصویب محور",
  editAxisContent: "ویرایش محتوای محور",
  ratifyTab: "تصویب محورها",
  assignTab: "ارجاع مأموریت",
  createMission: "ایجاد مأموریت",
  pickTopicForMission: "انتخاب محور برای مأموریت",
  allAssignableTopics: "همه محورها",
  newTopicsOnly: "فقط جدید (بدون مأموریت)",
  searchTopicPlaceholder: "جستجو کد، عنوان محور...",
  assignPageTitle: "ارجاع مأموریت",
  assignGateMessage: "این محور قابل ارجاع نیست. فقط محورهای تصویب‌شده با مهلت معتبر (نه منقضی، بایگانی، رد‌شده یا بسته‌شده) می‌توانند مأموریت جدید بگیرند.",
  topicCompletedMessage: "این محور تکمیل شده است. ارجاع جدید ثبت نمی‌شود.",
  completeTopic: "تکمیل موضوع",
  completeTopicConfirm: "با تکمیل موضوع، ارجاع جدید برای این محور ثبت نمی‌شود. مأموریت‌های در جریان بدون لغو ادامه می‌یابند.",
  topicDeadlinePassed: "مهلت این محور تمام شده",
  extendDeadline: "تمدید مهلت",
  proposeTopic: "پیشنهاد موضوع",
  registerProposal: "ثبت پیشنهاد",
  activeTab: "فعال",
  archiveTab: "آرشیو",
  archiveLink: "آرشیو",
  archiveBack: "بازگشت به فعال",
  archiveHint: "رد شده، تکمیل‌شده و بایگانی‌شده — فقط از بخش آرشیو.",
  readyToAssign: "آماده ارجاع",
  inAnalysisFlow: "در جریان تحلیل",
  createMissionForRatified: "ایجاد مأموریت برای محور تصویب‌شده",
  myAxesPageTitle: "محورهای تحلیل من",
  manageAxesPageTitle: "مدیریت محورها",
  manageAxesMenu: "مدیریت محورها",
  topicsManagementPath: "/analysis/topics",
  missionManagementPageTitle: "مدیریت تحلیل‌ها",
  missionManagementMenu: "مدیریت تحلیل‌ها",
  missionManageDetailTitle: "مدیریت تحلیل",
  missionManageDetailHelpTitle: "راهنمای مدیریت تحلیل",
  missionsManagementPath: "/analysis/missions",
  newAxis: "محور جدید",
  registerAxis: "ثبت محور",
  editAxis: "ویرایش محور",
  proposeAxisMenu: "ثبت محور تحلیل",
  ratifyAxesMenu: "تصویب محورها",
  ratifyAxesPath: "/analysis/topics?tab=queue",
  axisLabelPrefix: "محور:",
  finalApproval: "تایید نهایی",
};

export const WORKFLOW_STEPS = [
  { id: "propose", label: "پیشنهاد موضوع" },
  { id: "ratify", label: "تصویب" },
  { id: "assign", label: "ارجاع" },
  { id: "analyze", label: "تحلیل" },
  { id: "review", label: "بازبینی" },
  { id: "finalize", label: "تکمیل" },
];

export const BRIEF_TERMS = {
  pageTitle: "ثبت تحلیل و پیشنهاد موضوع",
  menuLabel: "ثبت تحلیل و پیشنهاد موضوع",
  inboxTab: "تحلیل‌های ثبت‌شده",
  bankTab: "بانک تحلیل",
  mySubmissions: "ثبت‌های من",
  submitBtn: "ارسال به مدیر تحلیل",
  submitTopicBtn: "ارسال پیشنهاد موضوع",
  entryModeSelf: "تحلیل خودم",
  entryModeExternal: "تحلیل دیگران (بارگذاری/نقل)",
  entryModeTopicProposal: "پیشنهاد موضوع",
  topicProposalTitle: "موضوع پیشنهادی",
  topicProposalDescription: "توضیح موضوع",
  topicProposalDescriptionHint: "شرح کوتاه موضوع — برای ایجاد محور تحلیل استفاده می‌شود",
  importanceReasonLabel: "دلیل اهمیت",
  importanceReasonHint: "اختیاری — چرا این موضوع مهم است؟",
  attributionLabel: "منبع / نویسنده",
  attributionHint: "نام شخص، نهاد، وب‌سایت یا هر منبع — هر قالبی مجاز است",
  compositionDateLabel: "تاریخ نگارش",
  compositionDateHint: "اختیاری — از تقویم شمسی انتخاب کنید؛ پیش‌فرض امروز",
  promoteTopic: "ارتقا به محور",
  promoteMission: "ارتقا به مأموریت",
  suggestAnalyst: "پیشنهاد نقش تحلیل‌گر",
  approveBank: "تأیید (ذخیره در بانک)",
  rejectBtn: "رد",
  editorApprove: "تأیید انتشار",
  publishBtn: "انتشار در پیام‌رسان",
  republishBtn: "انتشار مجدد",
  editBankContent: "ویرایش متن بانک",
  qualityPromising: "امیدوارکننده",
  qualityUseful: "مفید",
  qualityArchive: "بایگانی",
};

export const APPROVAL_DECISIONS = [
  { value: "approve", label: ANALYSIS_TERMS.ratify },
  { value: "reject", label: "رد" },
  { value: "needs_info", label: "برگشت برای اصلاح" },
  { value: "close", label: "بستن" },
];
