export const dashboardStyles = {
  widget: {
    borderRadius: 10,
    border: "1px solid",
    marginBottom: 8,
    overflow: "hidden",
  },
  widgetHeader: {
    padding: "10px 12px",
    display: "flex",
    justifyContent: "space-between",
    cursor: "pointer",
    alignItems: "center",
    gap: 8,
  },
  widgetBody: {
    padding: 12,
    borderTop: "1px solid rgba(128,128,128,0.1)",
  },
  widgetCtrlBtn: (theme, accent) => ({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
    height: 32,
    borderRadius: 6,
    border: `1px solid ${accent ? accent : theme.border}`,
    background: accent ? "rgba(14,165,233,0.12)" : "transparent",
    color: theme.text,
    cursor: "pointer",
  }),
  toolbarBtn: (theme, accent) => ({
    padding: "7px 12px",
    borderRadius: 8,
    border: `1px solid ${theme.border}`,
    background: accent ? accent : theme.card,
    color: accent ? "#fff" : theme.text,
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 11,
    fontWeight: 600,
  }),
  filterCard: {
    borderRadius: 10,
    border: "1px solid",
    padding: 12,
    marginBottom: 12,
  },
  inputGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    minWidth: 140,
  },
  label: {
    fontSize: 11,
    fontWeight: 500,
    opacity: 0.85,
  },
  select: {
    padding: "8px 10px",
    borderRadius: 8,
    border: "1px solid",
    fontFamily: "inherit",
    fontSize: 12,
  },
  datePickerWrapper: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minWidth: 220,
  },
  statsGrid: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
  },
  statBox: (color) => ({
    flex: "1 1 100px",
    padding: 12,
    background: "rgba(128,128,128,0.03)",
    borderRadius: 8,
    display: "flex",
    flexDirection: "column",
    gap: 4,
    borderRight: `4px solid ${color}`,
  }),
  dataTable: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: 11,
  },
  th: (theme) => ({
    padding: "8px 6px",
    textAlign: "right",
    opacity: 0.75,
    borderBottom: `1px solid ${theme.border}`,
    whiteSpace: "nowrap",
  }),
  td: (theme) => ({
    padding: "8px 6px",
    borderBottom: `1px solid ${theme.border}`,
    whiteSpace: "nowrap",
  }),
};
