/** پالت فرم ثبت گزارش یگان — تیره و روشن (هم‌راستا با تم تنظیمات سیستم) */

function buildDarkUnitStyles() {
  const inputStyle = {
    width: "100%",
    background: "#1e293b",
    border: "1px solid #334155",
    borderRadius: "8px",
    padding: "10px",
    color: "#fff",
    fontSize: "1em",
    outline: "none",
    boxSizing: "border-box",
  };

  return {
    headingOnCard: "#fff",
    subMuted: "#94a3b8",
    containerStyle: {
      padding: "15px 10px",
      background: "#020617",
      minHeight: "100vh",
      direction: "rtl",
      fontFamily: "Tahoma",
    },
    cardStyle: {
      background: "#0f172a",
      borderRadius: "14px",
      maxWidth: "480px",
      margin: "auto",
      border: "1px solid #1e293b",
      overflow: "hidden",
    },
    dateTopBar: {
      background: "#1e293b",
      color: "#38bdf8",
      padding: "8px 15px",
      fontSize: "12px",
      textAlign: "right",
      borderBottom: "1px solid #334155",
      fontWeight: "bold",
    },
    rejectedAlertStyle: {
      background: "rgba(239, 68, 68, 0.15)",
      borderBottom: "1px solid #ef4444",
      color: "#ef4444",
      padding: "12px 15px",
      display: "flex",
      flexDirection: "column",
      gap: "8px",
      fontSize: "12px",
      fontWeight: "bold",
    },
    goToTargetBtn: {
      background: "#ef4444",
      color: "#fff",
      border: "none",
      padding: "5px 10px",
      borderRadius: "5px",
      cursor: "pointer",
      fontSize: "11px",
      alignSelf: "flex-start",
      display: "inline-flex",
      alignItems: "center",
    },
    slimHeader: {
      background: "#1e293b",
      padding: "12px 15px",
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
    },
    miniBackBtn: {
      background: "rgba(56, 189, 248, 0.1)",
      border: "1px solid #38bdf8",
      color: "#38bdf8",
      padding: "4px",
      borderRadius: "6px",
      cursor: "pointer",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
    },
    unitBadge: {
      background: "#38bdf8",
      color: "#000",
      padding: "2px 8px",
      borderRadius: "5px",
      fontSize: "11px",
      fontWeight: "bold",
    },
    formContent: { padding: "18px" },
    inputWrapper: { marginBottom: "15px", position: "relative" },
    labelRow: {
      display: "flex",
      justifyContent: "space-between",
      marginBottom: "5px",
    },
    labelStyle: { color: "#94a3b8", fontSize: "12px", fontWeight: "bold" },
    inputStyle,
    selectStyle: { ...inputStyle, cursor: "pointer" },
    textareaStyle: { ...inputStyle, height: "110px", resize: "none" },
    priorityGroup: { display: "flex", gap: "10px", marginTop: "5px" },
    priorityBtn: {
      flex: 1,
      padding: "8px",
      borderRadius: "8px",
      fontSize: "12px",
      fontWeight: "bold",
      cursor: "pointer",
      transition: "all 0.2s",
      fontFamily: "inherit",
    },
    historyLink: {
      background: "none",
      border: "none",
      color: "#38bdf8",
      fontSize: "11px",
      cursor: "pointer",
      display: "flex",
      gap: "4px",
      alignItems: "center",
    },
    clearLink: {
      background: "none",
      border: "none",
      color: "#ef4444",
      fontSize: "11px",
      cursor: "pointer",
      display: "flex",
      gap: "4px",
      alignItems: "center",
      fontFamily: "inherit",
    },
    miniHistoryBox: {
      position: "absolute",
      top: "65px",
      width: "100%",
      background: "#1e293b",
      border: "1px solid #38bdf8",
      borderRadius: "10px",
      zIndex: 100,
      boxShadow: "0 10px 25px #000",
    },
    historyItem: {
      padding: "12px",
      borderBottom: "1px solid #334155",
      cursor: "pointer",
    },
    btnRow: { display: "flex", gap: "10px", marginTop: "15px" },
    sendBtn: {
      flex: 1,
      background: "#0ea5e9",
      color: "#fff",
      border: "none",
      padding: "12px",
      borderRadius: "10px",
      fontWeight: "bold",
      cursor: "pointer",
      fontFamily: "inherit",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "6px",
    },
    showListBtn: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "8px",
      background: "none",
      border: "1px solid #334155",
      color: "#64748b",
      padding: "10px",
      borderRadius: "10px",
      fontSize: "12px",
      cursor: "pointer",
      fontFamily: "inherit",
    },
    reportListContainer: {
      background: "#0f172a",
      width: "100%",
      maxWidth: "1000px",
      margin: "0 auto",
      padding: "15px",
      borderRadius: "12px",
    },
    panelTopBar: {
      display: "flex",
      justifyContent: "space-between",
      marginBottom: "15px",
      alignItems: "center",
      gap: "10px",
    },
    searchWrapper: {
      display: "flex",
      alignItems: "center",
      background: "#1e293b",
      borderRadius: "8px",
      padding: "0 10px",
      border: "1px solid #334155",
      flex: 1,
    },
    searchInput: {
      background: "none",
      border: "none",
      color: "#fff",
      padding: "8px",
      fontSize: "1em",
      outline: "none",
      width: "100%",
      fontFamily: "inherit",
    },
    closeBtn: {
      background: "#ef4444",
      color: "#fff",
      border: "none",
      padding: "8px",
      borderRadius: "8px",
      cursor: "pointer",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
    },
    printActionBtn: {
      background: "#10b981",
      color: "#fff",
      border: "none",
      padding: "8px 15px",
      borderRadius: "8px",
      fontWeight: "bold",
      cursor: "pointer",
      fontFamily: "inherit",
      display: "inline-flex",
      alignItems: "center",
    },
    finalTable: {
      width: "100%",
      borderCollapse: "collapse",
      color: "#cbd5e1",
      border: "1px solid #334155",
      tableLayout: "fixed",
    },
    thStyle: {
      padding: "12px",
      border: "1px solid #334155",
      color: "#94a3b8",
      fontSize: "1em",
      textAlign: "center",
    },
    catRow: {
      background: "rgba(56, 189, 248, 0.1)",
      color: "#38bdf8",
      fontWeight: "bold",
      textAlign: "right",
      padding: "12px 15px",
      border: "1px solid #334155",
    },
    dataRow: { borderBottom: "1px solid #334155" },
    tdStyleCenter: {
      padding: "12px",
      border: "1px solid #334155",
      textAlign: "center",
      color: "#0ea5e9",
      fontWeight: "bold",
      verticalAlign: "top",
      overflowWrap: "anywhere",
    },
    tdStyleBold: {
      padding: "12px",
      border: "1px solid #334155",
      fontWeight: "bold",
      verticalAlign: "top",
      overflowWrap: "anywhere",
    },
    tdStyleJustify: {
      padding: "12px",
      border: "1px solid #334155",
      textAlign: "justify",
      lineHeight: "1.7",
      fontSize: "12px",
      verticalAlign: "top",
      overflowWrap: "anywhere",
    },
    editIconBtn: {
      background: "none",
      border: "none",
      color: "#f59e0b",
      cursor: "pointer",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
    },
    modalOverlay: {
      position: "fixed",
      top: 0,
      left: 0,
      width: "100%",
      height: "100%",
      background: "rgba(0,0,0,0.85)",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      zIndex: 1000,
    },
    modalContent: {
      background: "#0f172a",
      padding: "25px",
      borderRadius: "15px",
      width: "95%",
      border: "1px solid #334155",
      boxSizing: "border-box",
    },
    closeModalBtn: {
      width: "100%",
      background: "#334155",
      color: "#fff",
      border: "none",
      padding: "10px",
      borderRadius: "8px",
      marginTop: "15px",
      cursor: "pointer",
      fontFamily: "inherit",
    },
    backBtn: {
      flex: 1,
      background: "#334155",
      color: "#fff",
      border: "none",
      padding: "12px",
      borderRadius: "10px",
      cursor: "pointer",
      fontFamily: "inherit",
    },
    redWarningBox: {
      background: "rgba(239, 68, 68, 0.08)",
      border: "1px solid rgba(239, 68, 68, 0.25)",
      borderRadius: "8px",
      padding: "12px",
      color: "#f87171",
      marginBottom: "15px",
    },
    helpBodyText: "#cbd5e1",
    helpHeadingBorder: "#334155",
    rejectedCardBg: "#1e293b",
    rejectedInnerTextBg: "#0f172a",
    rejectedInnerTextColor: "#cbd5e1",
    emptyStateColor: "#cbd5e1",
  };
}

function buildLightUnitStyles(d) {
  const L = {
    border: "#cbd5e1",
    card: "#ffffff",
    page: "#e8eef4",
    bar: "#f1f5f9",
    input: "#ffffff",
    inputText: "#0f172a",
  };
  const inputStyle = {
    width: "100%",
    background: L.input,
    border: `1px solid ${L.border}`,
    borderRadius: "8px",
    padding: "10px",
    color: L.inputText,
    fontSize: "1em",
    outline: "none",
    boxSizing: "border-box",
  };

  return {
    ...d,
    headingOnCard: "#0f172a",
    subMuted: "#64748b",
    containerStyle: {
      padding: "15px 10px",
      background: L.page,
      minHeight: "100vh",
      direction: "rtl",
      fontFamily: "Tahoma",
    },
    cardStyle: {
      background: L.card,
      borderRadius: "14px",
      maxWidth: "480px",
      margin: "auto",
      border: `1px solid ${L.border}`,
      overflow: "hidden",
    },
    dateTopBar: {
      background: L.bar,
      color: "#0369a1",
      padding: "8px 15px",
      fontSize: "12px",
      textAlign: "right",
      borderBottom: `1px solid ${L.border}`,
      fontWeight: "bold",
    },
    slimHeader: {
      background: L.bar,
      padding: "12px 15px",
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      borderBottom: `1px solid ${L.border}`,
    },
    labelStyle: { color: "#475569", fontSize: "12px", fontWeight: "bold" },
    inputStyle,
    selectStyle: { ...inputStyle, cursor: "pointer" },
    textareaStyle: { ...inputStyle, height: "110px", resize: "none" },
    miniHistoryBox: {
      position: "absolute",
      top: "65px",
      width: "100%",
      background: L.card,
      border: "1px solid #38bdf8",
      borderRadius: "10px",
      zIndex: 100,
      boxShadow: "0 10px 25px rgba(15,23,42,0.12)",
    },
    historyItem: {
      padding: "12px",
      borderBottom: `1px solid ${L.border}`,
      cursor: "pointer",
    },
    showListBtn: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: "8px",
      background: "none",
      border: `1px solid ${L.border}`,
      color: "#64748b",
      padding: "10px",
      borderRadius: "10px",
      fontSize: "12px",
      cursor: "pointer",
      fontFamily: "inherit",
    },
    reportListContainer: {
      background: L.card,
      width: "100%",
      maxWidth: "1000px",
      margin: "0 auto",
      padding: "15px",
      borderRadius: "12px",
      border: `1px solid ${L.border}`,
    },
    searchWrapper: {
      display: "flex",
      alignItems: "center",
      background: L.bar,
      borderRadius: "8px",
      padding: "0 10px",
      border: `1px solid ${L.border}`,
      flex: 1,
    },
    searchInput: {
      background: "none",
      border: "none",
      color: L.inputText,
      padding: "8px",
      fontSize: "1em",
      outline: "none",
      width: "100%",
      fontFamily: "inherit",
    },
    finalTable: {
      width: "100%",
      borderCollapse: "collapse",
      color: "#334155",
      border: `1px solid ${L.border}`,
      tableLayout: "fixed",
    },
    thStyle: {
      padding: "12px",
      border: `1px solid ${L.border}`,
      color: "#64748b",
      fontSize: "1em",
      textAlign: "center",
    },
    catRow: {
      background: "rgba(56, 189, 248, 0.12)",
      color: "#0369a1",
      fontWeight: "bold",
      textAlign: "right",
      padding: "12px 15px",
      border: `1px solid ${L.border}`,
    },
    dataRow: { borderBottom: `1px solid ${L.border}` },
    tdStyleCenter: {
      padding: "12px",
      border: `1px solid ${L.border}`,
      textAlign: "center",
      color: "#0369a1",
      fontWeight: "bold",
      verticalAlign: "top",
      overflowWrap: "anywhere",
    },
    tdStyleBold: {
      padding: "12px",
      border: `1px solid ${L.border}`,
      fontWeight: "bold",
      verticalAlign: "top",
      overflowWrap: "anywhere",
      color: "#0f172a",
    },
    tdStyleJustify: {
      padding: "12px",
      border: `1px solid ${L.border}`,
      textAlign: "justify",
      lineHeight: "1.7",
      fontSize: "12px",
      verticalAlign: "top",
      overflowWrap: "anywhere",
      color: "#334155",
    },
    modalContent: {
      background: L.card,
      padding: "25px",
      borderRadius: "15px",
      width: "95%",
      border: `1px solid ${L.border}`,
      boxSizing: "border-box",
    },
    closeModalBtn: {
      width: "100%",
      background: "#e2e8f0",
      color: "#0f172a",
      border: `1px solid ${L.border}`,
      padding: "10px",
      borderRadius: "8px",
      marginTop: "15px",
      cursor: "pointer",
      fontFamily: "inherit",
    },
    backBtn: {
      flex: 1,
      background: "#e2e8f0",
      color: "#0f172a",
      border: `1px solid ${L.border}`,
      padding: "12px",
      borderRadius: "10px",
      cursor: "pointer",
      fontFamily: "inherit",
    },
    helpBodyText: "#334155",
    helpHeadingBorder: L.border,
    rejectedCardBg: "#fef2f2",
    rejectedInnerTextBg: "#f8fafc",
    rejectedInnerTextColor: "#334155",
    emptyStateColor: "#64748b",
  };
}

let _darkCache;

export function getUnitReportFormStyles(isDark) {
  if (!_darkCache) _darkCache = buildDarkUnitStyles();
  if (isDark) return _darkCache;
  return buildLightUnitStyles(_darkCache);
}
